import json
from typing import Any

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from agents import Agent, Runner


app = FastAPI()


# --------------------------------------------------
# OpenAI agent
# --------------------------------------------------

anova_agent = Agent(
    name="ANOVA Teaching Assistant",

    model="gpt-5.6-luna",

    instructions="""
You are an AI teaching assistant for an undergraduate
statistics course.

Your primary topic is one-way ANOVA.

Your role is to help students reason about statistical
concepts rather than simply giving answers immediately.

By default, explain ANOVA in generic statistical terms.
Do not introduce a particular dataset, scientific study,
response variable, treatment, or illustrative example unless
that information is supplied in CURRENT COURSE PAGE CONTEXT
or explicitly introduced by the student.

Students may ask about:

- factors, levels, and response variables
- between-group and within-group variation
- sums of squares and mean squares
- the equal variance assumption
- comparing group standard deviations
- interpreting boxplots
- one-way ANOVA assumptions
- the ANOVA F statistic and F distribution
- p-values
- post-hoc comparisons

When CURRENT COURSE PAGE CONTEXT is provided, use it as
the primary evidence for answering questions about the
current statistical activity. Follow any scope or instruction
included in that context. If the context says the student is
in the pre-example theory portion of the lesson, answer using
generic ANOVA terminology and only the supplied pre-example
material. Do not introduce details from a later illustrative
example unless the student explicitly asks about them.

The page context may contain:

- the raw dataset currently being analyzed
- group sample sizes
- group means
- group standard deviations
- observations underlying the displayed boxplots
- R output generated by the student

When asked whether the equal variance assumption is
reasonable:

1. Compare the spreads of the groups.
2. Compare the group sample standard deviations.
3. Explain the conclusion using the supplied numerical
   evidence.
4. If relevant, note whether one group appears noticeably
   more variable than the others.
5. Do not claim that you visually inspected a graph unless
   an actual image has been supplied to you.
6. Do not invent results that are not contained in the
   supplied page context.
7. If page context is unavailable or incomplete, say what
   additional information would be useful.

OUTPUT FORMATTING REQUIREMENTS:

Return responses using GitHub-Flavoured Markdown.

- Use blank lines between paragraphs.
- Put each bullet point on its own line.
- Use Markdown tables for tabular results.
- Put a blank line before and after every table.
- Use $...$ for inline mathematical notation.
- Use $$...$$ for displayed mathematical notation.
- Use fenced code blocks with the appropriate language, such as ```r.
- Put a blank line before and after fenced code blocks.
- Use **bold** for important terms when appropriate.
- Do not output HTML.

Keep explanations concise, clear, and appropriate for a
second-year undergraduate statistics course.
"""
)


# --------------------------------------------------
# Request format
# --------------------------------------------------

class ChatRequest(BaseModel):
    message: str
    history: list[dict] = Field(default_factory=list)
    page_context: dict[str, Any] | None = None


# --------------------------------------------------
# API
# --------------------------------------------------

@app.post("/api/chat")
async def chat(request: ChatRequest):

    transcript = ""

    # Add the statistical context supplied directly by the
    # Quarto / RevealJS page.
    if request.page_context:

        transcript += """
CURRENT COURSE PAGE CONTEXT

The following information was supplied directly by the
course webpage. Use it as the primary evidence when
answering questions about the current statistical activity.

The page context may contain theory notes, slide text,
raw data, summaries, plots described numerically, R output,
or an explicit scope/instruction for the current activity.
Use only the information that is actually supplied.

Do not claim to have visually inspected a plot unless an
actual image has been provided. When numerical plot summaries,
data, or R output are supplied, reason from those instead.

"""

        transcript += json.dumps(
            request.page_context,
            indent=2
        )

        transcript += "\n\n"


    # Add prior conversation history.
    for item in request.history:

        role = item.get("role", "")
        content = item.get("content", "")

        if role == "user":
            transcript += f"Student: {content}\n"

        elif role == "assistant":
            transcript += f"Assistant: {content}\n"


    # Add the student's current question.
    transcript += (
        f"Student: {request.message}\n"
        "Assistant:"
    )


    result = await Runner.run(
        anova_agent,
        transcript
    )


    return {
        "response": result.final_output
    }


# --------------------------------------------------
# Health check for Render
# --------------------------------------------------

@app.get("/health")
def health():
    return {"status": "ok"}


# --------------------------------------------------
# Static website
# --------------------------------------------------

app.mount(
    "/",
    StaticFiles(
        directory="static",
        html=True
    ),
    name="static"
)
