import json
from typing import Any

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from agents import Agent, Runner


app = FastAPI()


# --------------------------------------------------
# OpenAI agent
# --------------------------------------------------

anova_agent = Agent(
    name="ANOVA Teaching Assistant",

    model="gpt-5.6-luna",

    instructions="""
You are an AI teaching assistant for an undergraduate
statistics course.

Your primary topic is one-way ANOVA.

Your role is to help students reason about statistical
concepts rather than simply giving answers immediately.

By default, explain ANOVA in generic statistical terms.
Do not introduce a particular dataset, scientific study,
response variable, treatment, or illustrative example unless
that information is supplied in CURRENT COURSE PAGE CONTEXT
or explicitly introduced by the student.

Students may ask about:

- factors, levels, and response variables
- between-group and within-group variation
- sums of squares and mean squares
- the equal variance assumption
- comparing group standard deviations
- interpreting boxplots
- one-way ANOVA assumptions
- the ANOVA F statistic and F distribution
- p-values
- post-hoc comparisons

When CURRENT COURSE PAGE CONTEXT is provided, use it as
the primary evidence for answering questions about the
current statistical activity. Follow any scope or instruction
included in that context.

CONTEXT MODES:

1. PRE-EXAMPLE THEORY MODE
If the context says the student is in the pre-example theory
portion of the lesson, answer using generic ANOVA terminology
and only the supplied pre-example material. Do not introduce
details from a later illustrative example unless the student
explicitly asks about them.

2. EXAMPLE / ACTIVITY MODE
If the context is for a specific activity or illustrative
example, explain the relevant ANOVA idea and use the supplied
example, data, summaries, or R output as evidence.

3. WHOLE-DECK MODE
If the context scope is the entire slide deck, treat the deck
as having TWO complementary layers:

- generic one-way ANOVA concepts, notation, assumptions,
  reasoning, and interpretation; and
- the illustrative example showing how those generic ideas
  are applied in practice.

For a whole-deck summary, overview, recap, or broad question,
do not summarize only in terms of the illustrative example.
Cover BOTH layers. State the generic ANOVA idea first, then
connect it to the illustrative example where appropriate.

For a specific conceptual question in whole-deck mode, first
answer in generic statistical terms and then briefly show how
the concept appears in the supplied example, when the example
contains relevant evidence. Keep generic principles distinct
from example-specific facts.

The page context may contain:

- the raw dataset currently being analyzed
- group sample sizes
- group means
- group standard deviations
- observations underlying the displayed boxplots
- R output generated by the student

When asked whether the equal variance assumption is
reasonable:

1. Compare the spreads of the groups.
2. Compare the group sample standard deviations.
3. Explain the conclusion using the supplied numerical
   evidence.
4. If relevant, note whether one group appears noticeably
   more variable than the others.
5. Do not claim that you visually inspected a graph unless
   an actual image has been supplied to you.
6. Do not invent results that are not contained in the
   supplied page context.
7. If page context is unavailable or incomplete, say what
   additional information would be useful.

OUTPUT FORMATTING REQUIREMENTS:

Return responses using GitHub-Flavoured Markdown.

- Use blank lines between paragraphs.
- Put each bullet point on its own line.
- Use Markdown tables for tabular results.
- Put a blank line before and after every table.
- Use $...$ for inline mathematical notation.
- Use $$...$$ for displayed mathematical notation.
- Use fenced code blocks with the appropriate language, such as ```r.
- Put a blank line before and after fenced code blocks.
- Use **bold** for important terms when appropriate.
- Do not output HTML.

Keep explanations concise, clear, and appropriate for a
second-year undergraduate statistics course.
"""
)


# --------------------------------------------------
# Request format
# --------------------------------------------------

class ChatRequest(BaseModel):
    message: str
    history: list[dict] = Field(default_factory=list)
    page_context: dict[str, Any] | None = None


# --------------------------------------------------
# API
# --------------------------------------------------

@app.post("/api/chat")
async def chat(request: ChatRequest):

    transcript = ""

    # Add the statistical context supplied directly by the
    # Quarto / RevealJS page.
    if request.page_context:

        transcript += """
CURRENT COURSE PAGE CONTEXT

The following information was supplied directly by the
course webpage. Use it as the primary evidence when
answering questions about the current statistical activity.

The page context may contain theory notes, slide text,
raw data, summaries, plots described numerically, R output,
or an explicit scope/instruction for the current activity.
Use only the information that is actually supplied.

Do not claim to have visually inspected a plot unless an
actual image has been provided. When numerical plot summaries,
data, or R output are supplied, reason from those instead.

"""

        activity = request.page_context.get("activity", {})
        scope = str(activity.get("scope", "")).strip().lower()
        mode = str(activity.get("mode", "")).strip().lower()

        if mode == "whole_deck" or scope == "entire slide deck":
            transcript += """
WHOLE-DECK RESPONSE REQUIREMENT

This is the final whole-deck assistant. The supplied material
contains both generic one-way ANOVA teaching content and an
illustrative example. Preserve both levels.

For summaries, recaps, overviews, or broad questions:
1. Explain the generic ANOVA ideas and reasoning.
2. Then connect those ideas to the illustrative example.
3. Do not replace the generic theory with an example-only
   summary.

For focused conceptual questions, explain the concept in
generic terms first and then use the illustrative example as
an application when relevant.

"""

        transcript += json.dumps(
            request.page_context,
            indent=2
        )

        transcript += "\n\n"


    # Add prior conversation history.
    for item in request.history:

        role = item.get("role", "")
        content = item.get("content", "")

        if role == "user":
            transcript += f"Student: {content}\n"

        elif role == "assistant":
            transcript += f"Assistant: {content}\n"


    # Add the student's current question.
    transcript += (
        f"Student: {request.message}\n"
        "Assistant:"
    )


    result = await Runner.run(
        anova_agent,
        transcript
    )


    return {
        "response": result.final_output
    }


# --------------------------------------------------
# Health check for Render
# --------------------------------------------------

@app.get("/health")
def health():
    return {"status": "ok"}


# --------------------------------------------------
# Static website
# --------------------------------------------------

app.mount(
    "/",
    StaticFiles(
        directory="static",
        html=True
    ),
    name="static"
)
